### ISSUE TITLE
dependency overrides

### ISSUE THREAD

**Issue by cjdoris** [JuliaPy/CondaPkg.jl#117]
Allow something like
```toml
[deps.somepackage]
version = ">=1.2, <2"
override = true
```
in CondaPkg.toml. The flag `override=true` has no effect unless it's in the top-level environment, in which case this dependency overrides any other dependencies for the same package name. And similar for pip deps.

Also some mechanism to avoid installing a package? Maybe a special `version = "skip"`?
